const mainArea=document.getElementById("mainArea"),lessonList=document.getElementById("lessonList");
const SUPABASE_URL="https://gonfodbllgdzuuvnkdko.supabase.co",SUPABASE_ANON_KEY="sb_publishable_PY57jZeJiAIaJSHDPrbCeg_r1eC4FC8",STUDENT_ID="savyon",PROGRESS_TABLE="progress";
let supabaseClient=null,progressCache=[];
function setConnStatus(ok,msg){const el=document.getElementById("connStatus");if(!el)return;el.textContent=msg;el.className=ok?"ok":"err"}
function initSupabase(){if(window.supabase&&window.supabase.createClient){supabaseClient=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);setConnStatus(true,"מחובר ל-Supabase")}else{console.error("Supabase library not loaded");setConnStatus(false,"שגיאה: ספריית Supabase לא נטענה. בדוק חיבור לאינטרנט ורענן את הדף.")}}
function esc(t){return String(t??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;")}
function norm(t){return String(t||"").trim().replace(/\s+/g," ").replace(/[.?!,;:'"״׳]/g,"").toLowerCase()}
function letter(i){return["א","ב","ג","ד"][i]||""}
async function loadProgress(){if(!supabaseClient)return;const{data,error}=await supabaseClient.from(PROGRESS_TABLE).select("*").eq("student_id",STUDENT_ID).order("updated_at",{ascending:false});if(error){console.error(error);progressCache=[];setConnStatus(false,"שגיאה בטעינת נתונים מ-Supabase. בדוק שהרצת את קובץ ה-SQL וששם הטבלה נכון.");return}progressCache=data||[]}
function getLessonProgress(id){return progressCache.find(r=>r.lesson_id===id)}
function renderLessonList(){lessonList.innerHTML="";LESSONS.forEach((lesson,i)=>{const b=document.createElement("button");b.className="lesson-btn";b.textContent=`${i+1}. ${lesson.title}${getLessonProgress(lesson.id)?" ✓":""}`;b.onclick=()=>renderLesson(lesson);lessonList.appendChild(b)})}
function renderHome(){const completed=progressCache.length,avg=completed?Math.round(progressCache.reduce((s,r)=>s+Number(r.percent||0),0)/completed):0;const recent=progressCache.slice(0,5).map(r=>`<tr><td>${esc(r.lesson_title||r.lesson_id)}</td><td>${esc(r.score)}/${esc(r.total)}</td><td>${esc(r.percent)}%</td><td>${r.updated_at?new Date(r.updated_at).toLocaleString("he-IL"):""}</td></tr>`).join("");mainArea.innerHTML=`<h2>דף הבית</h2><div class="card"><p>שיעורים שהושלמו: <b>${completed}</b> מתוך <b>${LESSONS.length}</b></p><p>ממוצע ציונים: <b>${avg}%</b></p></div><h3>ציונים אחרונים</h3>${completed?`<table><thead><tr><th>שיעור</th><th>ציון</th><th>אחוז</th><th>תאריך</th></tr></thead><tbody>${recent}</tbody></table>`:`<p>בחר שיעור מהרשימה בצד ימין.</p>`}`}
function renderLesson(lesson){let h=`<h2>${esc(lesson.title)}</h2><p class="small">${esc(lesson.unit||"")}</p><h3>אוצר מילים</h3><ul>${lesson.vocabulary.map(v=>`<li><b>${esc(v[0])}</b> — ${esc(v[1])}</li>`).join("")}</ul><h3>טקסט</h3><div class="reading-text">${lesson.reading}</div><h3>שאלות הבנת הנקרא</h3>`;lesson.comprehension.forEach((q,i)=>{h+=`<div class="question"><p><b>${i+1}. ${esc(q[0])}</b></p>${q[1].map((a,j)=>`<label><input type="radio" name="q${i}" value="${j}"> ${letter(j)}. ${esc(a)}</label><br>`).join("")}</div>`});if(lesson.grammar?.length){h+="<h3>דקדוק</h3>";lesson.grammar.forEach((q,i)=>{h+=`<div class="question"><p><b>${i+1}. ${esc(q[0])}</b></p>${q[1].map((a,j)=>`<label><input type="radio" name="g${i}" value="${j}"> ${letter(j)}. ${esc(a)}</label><br>`).join("")}</div>`})}if(lesson.cloze?.length){h+=`<h3>השלמת מילים</h3><p><b>בנק מילים:</b> ${esc(lesson.clozeBank.join(" | "))}</p>`;lesson.cloze.forEach((q,i)=>{h+=`<div class="question"><label>${i+1}. ${esc(q[0])}<input id="cloze${i}" type="text" autocomplete="off"></label></div>`})}h+=`<button class="main-btn" onclick="checkLesson('${esc(lesson.id)}')">בדוק שיעור</button><div id="resultBox"></div>`;mainArea.innerHTML=h}
function collect(lesson){let score=0,total=0;const mistakes=[],wrongWords=[];lesson.comprehension.forEach((q,i)=>{total++;const c=document.querySelector(`input[name="q${i}"]:checked`),given=c?Number(c.value):null,correct=Number(q[2]);if(given===correct)score++;else mistakes.push({section:"הבנת הנקרא",questionNumber:i+1,question:q[0],given:given===null?"לא נבחרה תשובה":`${letter(given)}. ${q[1][given]}`,correct:`${letter(correct)}. ${q[1][correct]}`})});lesson.grammar?.forEach((q,i)=>{total++;const c=document.querySelector(`input[name="g${i}"]:checked`),given=c?Number(c.value):null,correct=Number(q[2]);if(given===correct)score++;else mistakes.push({section:"דקדוק",questionNumber:i+1,question:q[0],given:given===null?"לא נבחרה תשובה":`${letter(given)}. ${q[1][given]}`,correct:`${letter(correct)}. ${q[1][correct]}`})});lesson.cloze?.forEach((q,i)=>{total++;const input=document.getElementById(`cloze${i}`),given=input?input.value.trim():"",correct=q[1];if(norm(given)===norm(correct))score++;else{mistakes.push({section:"השלמת מילים",questionNumber:i+1,question:q[0],given:given||"לא נכתבה תשובה",correct});wrongWords.push({lesson_id:lesson.id,lesson_title:lesson.title,prompt:q[0],user_answer:given||"",correct_answer:correct})}});return{score,total,percent:total?Math.round(score/total*100):0,mistakes,wrongWords}}
async function save(lesson,r){if(!supabaseClient)return false;const payload={student_id:STUDENT_ID,lesson_id:lesson.id,lesson_title:lesson.title,score:r.score,total:r.total,percent:r.percent,mistakes:r.mistakes,wrong_words:r.wrongWords,completed_at:new Date().toISOString(),updated_at:new Date().toISOString()};const{error}=await supabaseClient.from(PROGRESS_TABLE).upsert(payload,{onConflict:"student_id,lesson_id"});if(error){console.error(error);return false}await loadProgress();renderLessonList();return true}
async function checkLesson(id){const lesson=LESSONS.find(l=>l.id===id),r=collect(lesson);const mistakes=r.mistakes.length?`<h3>טעויות</h3>${r.mistakes.map(m=>`<div class="question"><p class="wrong">❌ ${esc(m.section)} ${esc(m.questionNumber)}</p><p>${esc(m.question)}</p><p>התשובה שלך: <b>${esc(m.given)}</b></p><p>התשובה הנכונה: <b>${esc(m.correct)}</b></p></div>`).join("")}`:`<p class="correct">כל הכבוד — אין טעויות.</p>`;document.getElementById("resultBox").innerHTML=`<h3>ציון: ${r.score}/${r.total} — ${r.percent}%</h3>${mistakes}<p id="saveStatus">שומר ל-Supabase...</p>`;document.getElementById("saveStatus").textContent=await save(lesson,r)?"נשמר ב-Supabase.":"השמירה נכשלה. בדוק שהרצת את קובץ ה-SQL."}
function renderQuestionMistakesReview(){const items=progressCache.flatMap(r=>(r.mistakes||[]).map(m=>({...m,lesson_title:r.lesson_title})));mainArea.innerHTML=items.length?`<h2>חזרה על שאלות שטעיתי בהן</h2>${items.map((m,i)=>`<div class="question"><p><b>${i+1}. ${esc(m.lesson_title)} — ${esc(m.section)} ${esc(m.questionNumber)}</b></p><p>${esc(m.question)}</p><p>התשובה שלך: <span class="wrong">${esc(m.given)}</span></p><p>התשובה הנכונה: <span class="correct">${esc(m.correct)}</span></p></div>`).join("")}`:`<h2>חזרה על שאלות שטעיתי בהן</h2><p>אין עדיין שאלות שגויות לחזרה.</p>`}
function renderWrongWordsReview(){const words=progressCache.flatMap(r=>r.wrong_words||[]);mainArea.innerHTML=words.length?`<h2>חזרה על מילים שטעיתי בהן</h2>${words.map((w,i)=>`<div class="question"><p><b>${i+1}. ${esc(w.lesson_title)}</b></p><p>${esc(w.prompt)}</p><p>התשובה שלך: <span class="wrong">${esc(w.user_answer||"לא נכתבה תשובה")}</span></p><p>התשובה הנכונה: <span class="correct">${esc(w.correct_answer)}</span></p></div>`).join("")}`:`<h2>חזרה על מילים שטעיתי בהן</h2><p>אין עדיין מילים שגויות לחזרה.</p>`}
async function resetProgress(){if(!confirm("האם למחוק את כל ההתקדמות?")||!supabaseClient)return;const{error}=await supabaseClient.from(PROGRESS_TABLE).delete().eq("student_id",STUDENT_ID);if(error){alert("האיפוס נכשל. בדוק הרשאת delete.");console.error(error);return}await loadProgress();renderLessonList();renderHome()}
async function startApp(){initSupabase();await loadProgress();document.getElementById("homeBtn").onclick=renderHome;document.getElementById("reviewBtn").onclick=renderWrongWordsReview;document.getElementById("reviewQuestionsBtn").onclick=renderQuestionMistakesReview;document.getElementById("resetBtn").onclick=resetProgress;renderLessonList();renderHome()}
startApp();